export const tableData = [
  {
    name: 'PICKUP_COLLECTION',
    columns: [
      {
        name: '_ID',
        dataType: 'INTEGER',
        isPrimaryKey: true,
        autoIncrement: true,
        shouldNotAllowNull: true,
      },
      {
        name: 'id',
        dataType: 'TEXT',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: false,
      },
      {
        name: 'delivery_type',
        dataType: 'TINYINT(1) DEFAULT 0',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: true,
      },
      {
        name: 'is_multiple',
        dataType: 'TINYINT(1) DEFAULT 0',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: true,
      },
      {
        name: 'pref_pick_date',
        dataType: 'DATE',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: true,
      },
      {
        name: 'pref_pick_time',
        dataType: 'TIME',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: false,
      },
      {
        name: 'tracking_id',
        dataType: 'TEXT',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: false,
      },
      
      {
        name: 'sender_id',
        dataType: 'TEXT',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: false,
      },
      {
        name: 'created_date',
        dataType: 'DATE',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: false,
      },
      {
        name: 'created_time',
        dataType: 'TIME',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: false,
      },
      {
        name: 'total_cost',
        dataType: 'DOUBLE',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: false,
      },
      {
        name: 'paid_amount',
        dataType: 'DOUBLE',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: false,
      },
      {
        name: 'is_fully_paid',
        dataType: 'TINYINT(1) DEFAULT 0',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: false,
      },
      {
        name: 'paid_date',
        dataType: 'DATE',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: false,
      },
      {
        name: 'paid_time',
        dataType: 'TIME',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: false,
      },
      {
        name: 'job_stage',
        dataType: 'TINYINT(1) DEFAULT 0',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: false,
      },
      {
        name: 'audit_user',
        dataType: 'TEXT',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: false,
      },
      {
        name: 'audit_date',
        dataType: 'DATE',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: false,
      },
      {
        name: 'audit_time',
        dataType: 'TIME',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: false,
      },
      {
        name: 'received_method',
        dataType: 'TEXT',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: false,
      },
      {
        name: 'status',
        dataType: 'TINYINT(1) DEFAULT 1',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: false,
      },
      {
        name: 'mobile_serial_number',
        dataType: 'TEXT',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: false,
      },


    ],
  },
  {
    name: 'PACKAGE',
    columns: [
      
      {
        name: '_ID',
        dataType: 'INTEGER',
        isPrimaryKey: true,
        autoIncrement: true,
        shouldNotAllowNull: true,
      },
      {
        name: 'id',
        dataType: 'TEXT',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: false,
      },
      
      {
        name: 'sender_id',
        dataType: 'INTEGER',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: true,
      },
      {
        name: 'receiver_id',
        dataType: 'INTEGER',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: true,
      },
      {
        name: 'details',
        dataType: 'TEXT',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: true,
      },
      {
        name: 'special_instruct',
        dataType: 'TEXT',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: false,
      },
      {
        name: 'package_count',
        dataType: 'INTEGER',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: false,
      },
      {
        name: 'pieces_count',
        dataType: 'INTEGER',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: false,
      },
      {
        name: 'width',
        dataType: 'DOUBLE',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: false,
      },
      {
        name: 'height',
        dataType: 'DOUBLE',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: false,
      },
      {
        name: 'length',
        dataType: 'DOUBLE',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: false,
      },
      {
        name: 'weight',
        dataType: 'DOUBLE',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: false,
      },
      {
        name: 'is_new',
        dataType: 'TINYINT(1) DEFAULT 0',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: false,
      },
      {
        name: 'is_synced',
        dataType: 'TINYINT(1) DEFAULT 0',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: false,
      },
      {
        name: 'created_user',
        dataType: 'TEXT',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: false,
      },
      {
        name: 'created_date',
        dataType: 'DATE',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: false,
      },
      {
        name: 'created_time',
        dataType: 'TIME',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: false,
      },
      {
        name: 'pickup_user',
        dataType: 'TEXT',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: false,
      },
      {
        name: 'pickup_date',
        dataType: 'DATE',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: false,
      },
      {
        name: 'pickup_time',
        dataType: 'TIME',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: false,
      },
      {
        name: 'pickup_lat',
        dataType: 'DOUBLE',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: false,
      },
      {
        name: 'pickup_long',
        dataType: 'DOUBLE',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: false,
      },
      {
        name: 'delivery_user',
        dataType: 'TEXT',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: false,
      },
      {
        name: 'delivery_date',
        dataType: 'DATE',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: false,
      },
      {
        name: 'delivery_time',
        dataType: 'TIME',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: false,
      },
      {
        name: 'delivery_lat',
        dataType: 'DOUBLE',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: false,
      },
      {
        name: 'delivery_long',
        dataType: 'DOUBLE',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: false,
      },
      {
        name: 'job_stage',
        dataType: 'TINYINT(1) DEFAULT 0',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: false,
      },
      {
        name: 'collection_ID',
        dataType: 'INTEGER',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: true,
      },
      {
        name: 'tracking_id',
        dataType: 'INTEGER',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: false,
      },
      {
        name: 'job_status',
        dataType: 'TINYINT(1) DEFAULT 0',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: false,
      },
      {
        name: 'Payment_Mode_ID',
        dataType: 'TINYINT(1) DEFAULT 0',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: false,
      },
      {
        name: 'Payment_Mode_Des',
        dataType: 'TEXT',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: false,
      },
      {
        name: 'Package_amount',
        dataType: 'DOUBLE',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: false,
      },
      {
        name: 'issettle',
        dataType: 'TINYINT(1) DEFAULT 0',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: false,
      },
      {
        name: 'InquiryID',
        dataType: 'TEXT',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: false,
      },
      {
        name: 'AreaTypeID',
        dataType: 'INTEGER',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: false,
      },
      
      {
        name: 'PacakgeTypeID',
        dataType: 'INTEGER',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: false,
      },
      

    ],
  },
  {
    name: 'SENDER',
    columns: [
      {
        name: '_ID',
        dataType: 'INTEGER',
        isPrimaryKey: true,
        autoIncrement: true,
        shouldNotAllowNull: true,
      },
      {
        name: 'id',
        dataType: 'TEXT',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: false,
      },
      {
        name: 'sender_type',
        dataType: 'INTEGER',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: true,
      },
     
      {
        name: 'sender_name',
        dataType: 'TEXT',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: true,
      },
      {
        name: 'sender_mobile',
        dataType: 'TEXT',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: true,
      },
      {
        name: 'sender_mobile_alter',
        dataType: 'TEXT',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: false,
      },
      {
        name: 'sender_address_1',
        dataType: 'TEXT',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: false,
      },
      
      {
        name: 'sender_address_2',
        dataType: 'TEXT',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: false,
      },
      {
        name: 'sender_address_3',
        dataType: 'TEXT',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: false,
      },
      {
        name: 'is_new',
        dataType: 'TINYINT(1) DEFAULT 0',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: false,
      },
      {
        name: 'is_synced',
        dataType: 'TINYINT(1) DEFAULT 0',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: false,
      },
      {
        name: 'audit_user',
        dataType: 'TEXT',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: false,
      },
    
      {
        name: 'audit_date',
        dataType: 'DATE',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: false,
      },
      {
        name: 'audit_time',
        dataType: 'TIME',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: false,
      },
    ],
  },
  {
    name: 'COLLECTION_POINT',
    columns: [
      {
        name: '_ID',
        dataType: 'INTEGER',
        isPrimaryKey: true,
        autoIncrement: true,
        shouldNotAllowNull: true,
      },
      {
        name: 'id',
        dataType: 'TEXT',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: false,
      },
      {
        name: 'location_tpye',
        dataType: 'TINYINT(1) DEFAULT 0',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: true,
      },
      {
        name: 'address_1',
        dataType: 'TEXT',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: true,
      },
      {
        name: 'address_2',
        dataType: 'TEXT',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: true,
      },
      {
        name: 'address_3',
        dataType: 'TEXT',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: false,
      },
      {
        name: 'gps_lat',
        dataType: 'DOUBLE',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: false,
      },
      
      {
        name: 'gps_long',
        dataType: 'DOUBLE',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: false,
      },
      {
        name: 'is_new',
        dataType: 'TINYINT(1) DEFAULT 0',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: false,
      },
      {
        name: 'is_synced',
        dataType: 'TINYINT(1) DEFAULT 0',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: false,
      },
      {
        name: 'audit_user',
        dataType: 'TEXT',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: false,
      },
    
      {
        name: 'audit_date',
        dataType: 'DATE',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: false,
      },
      {
        name: 'audit_time',
        dataType: 'TIME',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: false,
      },
    ],
  },
  {
    name: 'ISSUES',
    columns: [
      {
        name: '_ID',
        dataType: 'INTEGER',
        isPrimaryKey: true,
        autoIncrement: true,
        shouldNotAllowNull: true,
      },
      {
        name: 'id',
        dataType: 'TEXT',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: false,
      },
      {
        name: 'package_id',
        dataType: 'INTEGER',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: true,
      },
      {
        name: 'collection_type',
        dataType: 'TINYINT(1) DEFAULT 0',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: true,
      },
      {
        name: 'issue_type_id',
        dataType: 'INTEGER',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: true,
      },
      {
        name: 'remarks',
        dataType: 'TEXT',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: false,
      },
      {
        name: 'is_new',
        dataType: 'TINYINT(1) DEFAULT 0',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: false,
      },
      {
        name: 'is_synced',
        dataType: 'TINYINT(1) DEFAULT 0',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: false,
      },
      {
        name: 'audit_user',
        dataType: 'TEXT',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: false,
      },
    
      {
        name: 'audit_date',
        dataType: 'DATE',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: false,
      },
      {
        name: 'audit_time',
        dataType: 'TIME',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: false,
      },
    ],
  },
  {
    name: 'ISSUE_TYPE',
    columns: [
      {
        name: 'id',
        dataType: 'INTEGER',
        isPrimaryKey: true,
        autoIncrement: true,
        shouldNotAllowNull: true,
      },
      {
        name: 'collection_type',
        dataType: 'TINYINT(1) DEFAULT 0',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: true,
      },
      {
        name: 'issue_name',
        dataType: 'TEXT',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: true,
      },
      {
        name: 'is_act',
        dataType: 'TINYINT(1) DEFAULT 1',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: true,
      },
      {
        name: 'is_deleted',
        dataType: 'TINYINT(1) DEFAULT 0',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: false,
      },
    ],
  },
  {
    name: 'PACKAGE_BARCODE',
    columns: [
      {
        name: '_ID',
        dataType: 'INTEGER',
        isPrimaryKey: true,
        autoIncrement: true,
        shouldNotAllowNull: true,
      },
      {
        name: 'id',
        dataType: 'TEXT',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: false,
      },
      {
        name: 'package_id',
        dataType: 'INTEGER',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: true,
      },
      {
        name: 'image',
        dataType: 'BLOB DEFAULT NULL',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: false,
      },
      {
        name: 'barcode_id',
        dataType: 'TEXT',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: true,
      },
      {
        name: 'is_deleted',
        dataType: 'TINYINT(1) DEFAULT 0',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: false,
      },
      {
        name: 'is_new',
        dataType: 'TINYINT(1) DEFAULT 0',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: false,
      },
      {
        name: 'is_synced',
        dataType: 'TINYINT(1) DEFAULT 0',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: false,
      },
      
    ],
  },

  {
    name: 'SERVICE_CHARGES',
    columns: [
      {
        name: '_ID',
        dataType: 'INTEGER',
        isPrimaryKey: true,
        autoIncrement: true,
        shouldNotAllowNull: true,
      },
      {
        name: 'id',
        dataType: 'TEXT',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: false,
      },
      {
        name: 'package_id',
        dataType: 'INTEGER',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: true,
      },
      {
        name: 'charge_type_id',
        dataType: 'INTEGER ',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: false,
      },
      {
        name: 'amount',
        dataType: 'DOUBLE',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: true,
      },
      {
        name: 'is_act',
        dataType: 'TINYINT(1) DEFAULT 0',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: false,
      },
      {
        name: 'is_new',
        dataType: 'TINYINT(1) DEFAULT 0',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: false,
      },
      {
        name: 'is_synced',
        dataType: 'TINYINT(1) DEFAULT 0',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: false,
      },
    ],
  },

  {
    name: 'SERVICE_CHARGE_TYPE',
    columns: [
     {
        name: '_ID',
        dataType: 'INTEGER',
        isPrimaryKey: true,
        autoIncrement: true,
        shouldNotAllowNull: true,
      },
      {
        name: 'id',
        dataType: 'TEXT',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: false,
      },
      {
        name: 'charge_name',
        dataType: 'TEXT',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: true,
      },
      
      {
        name: 'is_act',
        dataType: 'TINYINT(1) DEFAULT 0',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: false,
      },
     
    ],
  },
  {
    name: 'CASH_COLLECTION',
    columns: [
      {
        name: '_ID',
        dataType: 'INTEGER',
        isPrimaryKey: true,
        autoIncrement: true,
        shouldNotAllowNull: true,
      },
      {
        name: 'id',
        dataType: 'TEXT',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: false,
      },
      {
        name: 'package_id',
        dataType: 'INTEGER',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: true,
      },
      {
        name: 'total_amount',
        dataType: 'DOUBLE ',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: false,
      },
      {
        name: 'paid_amount',
        dataType: 'DOUBLE',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: true,
      },
      {
        name: 'paid_user',
        dataType: 'TEXT',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: false,
      },
      {
        name: 'collected_user',
        dataType: 'TEXT',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: false,
      },
      {
        name: 'paid_date',
        dataType: 'DATE',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: false,
      },
      {
        name: 'paid_time',
        dataType: 'TIME',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: false,
      },
    ],
  },
  {
    name: 'RECEIVER',
    columns: [
      {
        name: '_ID',
        dataType: 'INTEGER',
        isPrimaryKey: true,
        autoIncrement: true,
        shouldNotAllowNull: true,
      },
      {
        name: 'id',
        dataType: 'TEXT',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: false,
      },
      {
        name: 'recevier_name',
        dataType: 'TEXT',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: true,
      },
      {
        name: 'recevier_mobile',
        dataType: 'TEXT ',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: false,
      },
      {
        name: 'recevier_mobile_alter',
        dataType: 'TEXT',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: true,
      },
      {
        name: 'recevier_address_1',
        dataType: 'TEXT',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: false,
      },
      {
        name: 'recevier_address_2',
        dataType: 'TEXT',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: false,
      },
      {
        name: 'recevier_address_3',
        dataType: 'TEXT',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: false,
      },
  
      {
        name: 'is_new',
        dataType: 'TINYINT(1) DEFAULT 0',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: false,
      },
      {
        name: 'is_synced',
        dataType: 'TINYINT(1) DEFAULT 0',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: false,
      },
      {
        name: 'audit_user',
        dataType: 'TEXT',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: false,
      },
      {
        name: 'audit_date',
        dataType: 'DATE',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: false,
      },
      {
        name: 'audit_time',
        dataType: 'TIME',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: false,
      },
      {
        name: 'InquiryID',
        dataType: 'TEXT',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: false,
      },

      {
        name: 'DistrictId',
        dataType: 'INTEGER',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: false,
      },
      {
        name: 'MainCityID',
        dataType: 'INTEGER',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: false,
      },
      {
        name: 'CityID',
        dataType: 'INTEGER',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: false,
      },
      {
        name: 'Tempory_Credit_Status',
        dataType: 'INTEGER',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: false,
      },
      {
        name: 'Tempory_Credit_Outstanding',
        dataType: 'DOUBLE',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: false,
      },
    ],
  },
  {
    name: 'USER',
    columns: [
      {
        name: '_ID',
        dataType: 'INTEGER',
        isPrimaryKey: true,
        autoIncrement: true,
        shouldNotAllowNull: true,
      },
      {
        name: 'id',
        dataType: 'TEXT',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: false,
      },
      {
        name: 'user_id',
        dataType: 'TEXT',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: false,
      },
      {
        name: 'profile_name',
        dataType: 'TEXT',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: false,
      },
      {
        name: 'full_name',
        dataType: 'TEXT ',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: false,
      },
      {
        name: 'branch_id',
        dataType: 'INTEGER ',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: false,
      },
      {
        name: 'user_type',
        dataType: 'TINYINT',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: true,
      },
      {
        name: 'login_attempts',
        dataType: 'TINYINT',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: false,
      },
      {
        name: 'device_id',
        dataType: 'TEXT',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: false,
      },
      {
        name: 'login_date',
        dataType: 'DATE',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: false,
      },
      {
        name: 'login_time',
        dataType: 'TIME',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: false,
      },
      {
        name: 'is_act',
        dataType: 'TINYINT',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: false,
      },
      {
        name: 'hash_key',
        dataType: 'TEXT',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: false,
      },
    
      
    ],
  },

  {
    name: 'METER_READING',
    columns: [
      {
        name: '_ID',
        dataType: 'INTEGER',
        isPrimaryKey: true,
        autoIncrement: true,
        shouldNotAllowNull: true,
      },
      {
        name: 'user_id',
        dataType: 'INTEGER',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: false,
      },
      {
        name: 'readingType',
        dataType: 'TEXT',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: false,
      },
      {
        name: 'Creation_date',
        dataType: 'DATETIME ',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: false,
      },
      {
        name: 'branch_id',
        dataType: 'INTEGER ',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: false,
      },
      {
        name: 'longitude',
        dataType: 'DOUBLE',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: true,
      },
      {
        name: 'latitude',
        dataType: 'DOUBLE',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: false,
      },
      {
        name: 'reader_value',
        dataType: 'INTEGER',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: false,
      },
      {
        name: 'remark',
        dataType: 'TEXT',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: false,
      },
      {
        name: 'is_sync',
        dataType: 'TINYINT(1) DEFAULT 0',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: false,
      },
    
      
    ],
  },

  {
    name: 'GPS_LOG',
    columns: [
      {
        name: '_ID',
        dataType: 'INTEGER',
        isPrimaryKey: true,
        autoIncrement: true,
        shouldNotAllowNull: true,
      },
      {
        name: 'id',
        dataType: 'TEXT',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: false,
      },
      {
        name: 'user_id',
        dataType: 'INTEGER',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: false,
      },
      {
        name: 'gps_lat',
        dataType: 'DOUBLE',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: false,
      },
      {
        name: 'gps_long',
        dataType: 'DOUBLE ',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: false,
      },
      {
        name: 'gps_date',
        dataType: 'DATE ',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: false,
      },
      {
        name: 'gps_time',
        dataType: 'TIME',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: true,
      },
      {
        name: 'battery',
        dataType: 'DOUBLE',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: false,
      },
      {
        name: 'speed',
        dataType: 'DOUBLE',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: false,
      },
      {
        name: 'gps_type',
        dataType: 'TINYINT ',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: false,
      },
      {
        name: 'is_synced',
        dataType: 'TINYINT(1) DEFAULT 0',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: false,
      },
    
      
    ],
  },
  {
    name: 'PACAKGE_Type',
    columns: [
      {
        name: 'id',
        dataType: 'INTEGER',
        isPrimaryKey: true,
        autoIncrement: false,
        shouldNotAllowNull: true,
      },
      {
        name: 'description',
        dataType: 'TEXT',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: false,
      },
      {
        name: 'status',
        dataType: 'TINYINT(1) DEFAULT 0',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: false,
      },
    
      
    ],
  },
  {
    name: 'AREA_Type',
    columns: [
      {
        name: 'id',
        dataType: 'INTEGER',
        isPrimaryKey: true,
        autoIncrement: false,
        shouldNotAllowNull: true,
      },
      {
        name: 'description',
        dataType: 'TEXT',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: false,
      },
      {
        name: 'status',
        dataType: 'TINYINT(1) DEFAULT 0',
        isPrimaryKey: false,
        autoIncrement: false,
        shouldNotAllowNull: false,
      },
    
      
    ],
  },

  // {
  //   name: 'PICKUP_ISSUE_REASON',
  //   columns: [
  //     {
  //       name: '_ID',
  //       dataType: 'INTEGER',
  //       isPrimaryKey: true,
  //       autoIncrement: true,
  //       shouldNotAllowNull: true,
  //     },
  //     {
  //       name: 'id',
  //       dataType: 'TEXT',
  //       isPrimaryKey: false,
  //       autoIncrement: false,
  //       shouldNotAllowNull: false,
  //     },
  //     {
  //       name: 'description',
  //       dataType: 'TEXT',
  //       isPrimaryKey: false,
  //       autoIncrement: false,
  //       shouldNotAllowNull: false,
  //     },
  //     {
  //       name: 'status',
  //       dataType: 'INTEGER',
  //       isPrimaryKey: false,
  //       autoIncrement: false,
  //       shouldNotAllowNull: false,
  //     },
  //     {
  //       name: 'created_date',
  //       dataType: 'DATE ',
  //       isPrimaryKey: false,
  //       autoIncrement: false,
  //       shouldNotAllowNull: false,
  //     },
  //     {
  //       name: 'created_time',
  //       dataType: 'TIME',
  //       isPrimaryKey: false,
  //       autoIncrement: false,
  //       shouldNotAllowNull: true,
  //     },
  //   ],
  // },
  
 
]